language: python
python:
  - "3.7"

env:
  - PLATFORMIO_PROJECT_DIR=examples/blink

install:
  - pip install -U https://github.com/OS-Q/S03/archive/master.zip
  - pio platform install file://.

script:
  - pio run -d $PLATFORMIO_PROJECT_DIR
